# ==========================================
# POST-PROCESSING CONFIG
# ==========================================

# Inheritance
pipeline_config: /path/to/my_project/run_config.yaml

# Overrides (Optional)
# n_jobs: /1                                    # Overrides the n_jobs defined in pipeline_config
# allow_overwrite: false
# output_vol_path: #custom output path
# output_metadata_path: "filtered_meta.parquet"#custom output path

# Actions
steps:
  # TargetedStep: Removes objects outside this voxel range directly from metadata and volume
  - type: "size_filter"
    min_nvoxels: 1000
    # max_nvoxels: 50000

  # RescanStep: Expands labels. Writes a NEW volume and triggers a full metadata rescan afterward.
  - type: "expand_labels"
    distance: 3
    halo: 4  # Optional: Padding for chunk-boundary overlap, defaults to distance setting